unit mdata;

interface

uses
  System.SysUtils, System.Classes, Data.DB, Data.Win.ADODB,DateUtils;

type
  Tdata = class(TDataModule)
    ADOConnection1: TADOConnection;
    child: TADOQuery;
    childdata: TDataSource;
    childchild_id: TAutoIncField;
    childchild_cn: TIntegerField;
    childchild_fn: TWideStringField;
    childchild_ln: TWideStringField;
    childchild_f: TWideStringField;
    childchild_birth: TDateTimeField;
    childchild_adress: TWideStringField;
    childchild_born: TWideStringField;
    childchild_status: TWideStringField;
    childchild_city: TWideStringField;
    childchild_place: TWideStringField;
    childchild_year: TWideStringField;
    childphone: TWideStringField;
    childvaccin_m: TIntegerField;
    childfullname: TStringField;
    childchild_num: TIntegerField;
    years: TADOQuery;
    vaccin: TADOQuery;
    vaccindata: TDataSource;
    vaccinvaccin_id: TAutoIncField;
    vaccinvaccin_name: TWideStringField;
    vaccinvaccin_lot: TWideStringField;
    vaccinvaccin_month: TIntegerField;
    injection: TADOQuery;
    injectioninjection_id: TAutoIncField;
    injectionvaccin_name: TWideStringField;
    injectionchild_idi: TIntegerField;
    injectionvaccin_state: TWideStringField;
    injectionvaccin_place: TWideStringField;
    injectiondata: TDataSource;
    injectioninjection_date: TWideStringField;
    yearsyear_id: TAutoIncField;
    yearsyears: TWideStringField;
    vaccinvaccin_num: TIntegerField;
    injectionvaccin_no: TIntegerField;
    annexe3: TADOQuery;
    annexe3child_id: TAutoIncField;
    annexe3child_cn: TIntegerField;
    annexe3child_fn: TWideStringField;
    annexe3child_ln: TWideStringField;
    annexe3child_f: TWideStringField;
    annexe3child_birth: TDateTimeField;
    annexe3child_adress: TWideStringField;
    annexe3child_born: TWideStringField;
    annexe3child_status: TWideStringField;
    annexe3child_city: TWideStringField;
    annexe3child_place: TWideStringField;
    annexe3child_year: TWideStringField;
    annexe3phone: TWideStringField;
    annexe3vaccin_m: TIntegerField;
    childchild_salle: TWideStringField;
    annexe3child_salle: TWideStringField;
    fiche: TADOQuery;
    fichechild_id: TAutoIncField;
    fichechild_cn: TIntegerField;
    fichechild_fn: TWideStringField;
    fichechild_ln: TWideStringField;
    fichechild_f: TWideStringField;
    fichechild_birth: TDateTimeField;
    fichechild_adress: TWideStringField;
    fichechild_born: TWideStringField;
    fichechild_status: TWideStringField;
    fichechild_city: TWideStringField;
    fichechild_place: TWideStringField;
    fichechild_year: TWideStringField;
    fichephone: TWideStringField;
    fichevaccin_m: TIntegerField;
    fichechild_salle: TWideStringField;
    childage: TStringField;
    annexe2: TADOQuery;
    annexe2child_id: TAutoIncField;
    annexe2child_cn: TIntegerField;
    annexe2child_fn: TWideStringField;
    annexe2child_ln: TWideStringField;
    annexe2child_f: TWideStringField;
    annexe2child_birth: TDateTimeField;
    annexe2child_adress: TWideStringField;
    annexe2child_born: TWideStringField;
    annexe2child_status: TWideStringField;
    annexe2child_city: TWideStringField;
    annexe2child_place: TWideStringField;
    annexe2child_year: TWideStringField;
    annexe2phone: TWideStringField;
    annexe2vaccin_m: TIntegerField;
    annexe2child_salle: TWideStringField;
    childvaccin_y: TIntegerField;
    annexe3vaccin_y: TIntegerField;
    fichevaccin_y: TIntegerField;
    annexe2vaccin_y: TIntegerField;
    childv1: TWideStringField;
    childv2: TWideStringField;
    childv3: TWideStringField;
    childv4: TWideStringField;
    childv5: TWideStringField;
    childv6: TWideStringField;
    childv7: TWideStringField;
    childv8: TWideStringField;
    childv9: TWideStringField;
    childv10: TWideStringField;
    childv11: TWideStringField;
    childv12: TWideStringField;
    annexe3v1: TWideStringField;
    annexe3v2: TWideStringField;
    annexe3v3: TWideStringField;
    annexe3v4: TWideStringField;
    annexe3v5: TWideStringField;
    annexe3v6: TWideStringField;
    annexe3v7: TWideStringField;
    annexe3v8: TWideStringField;
    annexe3v9: TWideStringField;
    annexe3v10: TWideStringField;
    annexe3v11: TWideStringField;
    annexe3v12: TWideStringField;
    fichev1: TWideStringField;
    fichev2: TWideStringField;
    fichev3: TWideStringField;
    fichev4: TWideStringField;
    fichev5: TWideStringField;
    fichev6: TWideStringField;
    fichev7: TWideStringField;
    fichev8: TWideStringField;
    fichev9: TWideStringField;
    fichev10: TWideStringField;
    fichev11: TWideStringField;
    fichev12: TWideStringField;
    annexe2v1: TWideStringField;
    annexe2v2: TWideStringField;
    annexe2v3: TWideStringField;
    annexe2v4: TWideStringField;
    annexe2v5: TWideStringField;
    annexe2v6: TWideStringField;
    annexe2v7: TWideStringField;
    annexe2v8: TWideStringField;
    annexe2v9: TWideStringField;
    annexe2v10: TWideStringField;
    annexe2v11: TWideStringField;
    annexe2v12: TWideStringField;
    street: TADOQuery;
    streetdata: TDataSource;
    salles: TADOQuery;
    sallesdata: TDataSource;
    sallessalle_id: TAutoIncField;
    sallessalle_name: TWideStringField;
    streetstreet_id: TAutoIncField;
    streetstreet_name: TWideStringField;
    childchild_death: TWideStringField;
    annexe3child_death: TWideStringField;
    fichechild_death: TWideStringField;
    annexe2child_death: TWideStringField;
    stat: TADOQuery;
    child1: TADOQuery;
    child2: TADOQuery;
    child3: TADOQuery;
    child4: TADOQuery;
    statsatat_id: TAutoIncField;
    statv_child: TIntegerField;
    statcible_child: TIntegerField;
    statv1: TIntegerField;
    statv2: TIntegerField;
    statv3: TIntegerField;
    statv4: TIntegerField;
    statv5: TIntegerField;
    statv6: TIntegerField;
    statv7: TIntegerField;
    statv8: TIntegerField;
    statv9: TIntegerField;
    statv10: TIntegerField;
    statv11: TIntegerField;
    statv12: TIntegerField;
    statmonth_name: TWideStringField;
    stat2: TADOQuery;
    AutoIncField1: TAutoIncField;
    WideStringField1: TWideStringField;
    IntegerField1: TIntegerField;
    IntegerField2: TIntegerField;
    IntegerField3: TIntegerField;
    IntegerField4: TIntegerField;
    IntegerField5: TIntegerField;
    IntegerField6: TIntegerField;
    IntegerField7: TIntegerField;
    IntegerField8: TIntegerField;
    IntegerField9: TIntegerField;
    IntegerField10: TIntegerField;
    IntegerField11: TIntegerField;
    IntegerField12: TIntegerField;
    IntegerField13: TIntegerField;
    IntegerField14: TIntegerField;
    statall_child: TIntegerField;
    stat2all_child: TIntegerField;
    statsatat_month: TIntegerField;
    statstat_year: TIntegerField;
    stat2satat_month: TIntegerField;
    stat2stat_year: TIntegerField;
    stat1: TADOQuery;
    AutoIncField2: TAutoIncField;
    WideStringField2: TWideStringField;
    IntegerField15: TIntegerField;
    IntegerField16: TIntegerField;
    IntegerField17: TIntegerField;
    IntegerField18: TIntegerField;
    IntegerField19: TIntegerField;
    IntegerField20: TIntegerField;
    IntegerField21: TIntegerField;
    IntegerField22: TIntegerField;
    IntegerField23: TIntegerField;
    IntegerField24: TIntegerField;
    IntegerField25: TIntegerField;
    IntegerField26: TIntegerField;
    IntegerField27: TIntegerField;
    IntegerField28: TIntegerField;
    IntegerField29: TIntegerField;
    IntegerField30: TIntegerField;
    IntegerField31: TIntegerField;
    stat3: TADOQuery;
    AutoIncField3: TAutoIncField;
    WideStringField3: TWideStringField;
    IntegerField32: TIntegerField;
    IntegerField33: TIntegerField;
    IntegerField34: TIntegerField;
    IntegerField35: TIntegerField;
    IntegerField36: TIntegerField;
    IntegerField37: TIntegerField;
    IntegerField38: TIntegerField;
    IntegerField39: TIntegerField;
    IntegerField40: TIntegerField;
    IntegerField41: TIntegerField;
    IntegerField42: TIntegerField;
    IntegerField43: TIntegerField;
    IntegerField44: TIntegerField;
    IntegerField45: TIntegerField;
    IntegerField46: TIntegerField;
    IntegerField47: TIntegerField;
    IntegerField48: TIntegerField;
    stat4: TADOQuery;
    AutoIncField4: TAutoIncField;
    WideStringField4: TWideStringField;
    IntegerField49: TIntegerField;
    IntegerField50: TIntegerField;
    IntegerField51: TIntegerField;
    IntegerField52: TIntegerField;
    IntegerField53: TIntegerField;
    IntegerField54: TIntegerField;
    IntegerField55: TIntegerField;
    IntegerField56: TIntegerField;
    IntegerField57: TIntegerField;
    IntegerField58: TIntegerField;
    IntegerField59: TIntegerField;
    IntegerField60: TIntegerField;
    IntegerField61: TIntegerField;
    IntegerField62: TIntegerField;
    IntegerField63: TIntegerField;
    IntegerField64: TIntegerField;
    IntegerField65: TIntegerField;
    stat5: TADOQuery;
    AutoIncField5: TAutoIncField;
    WideStringField5: TWideStringField;
    IntegerField66: TIntegerField;
    IntegerField67: TIntegerField;
    IntegerField68: TIntegerField;
    IntegerField69: TIntegerField;
    IntegerField70: TIntegerField;
    IntegerField71: TIntegerField;
    IntegerField72: TIntegerField;
    IntegerField73: TIntegerField;
    IntegerField74: TIntegerField;
    IntegerField75: TIntegerField;
    IntegerField76: TIntegerField;
    IntegerField77: TIntegerField;
    IntegerField78: TIntegerField;
    IntegerField79: TIntegerField;
    IntegerField80: TIntegerField;
    IntegerField81: TIntegerField;
    IntegerField82: TIntegerField;
    stat6: TADOQuery;
    AutoIncField6: TAutoIncField;
    WideStringField6: TWideStringField;
    IntegerField83: TIntegerField;
    IntegerField84: TIntegerField;
    IntegerField85: TIntegerField;
    IntegerField86: TIntegerField;
    IntegerField87: TIntegerField;
    IntegerField88: TIntegerField;
    IntegerField89: TIntegerField;
    IntegerField90: TIntegerField;
    IntegerField91: TIntegerField;
    IntegerField92: TIntegerField;
    IntegerField93: TIntegerField;
    IntegerField94: TIntegerField;
    IntegerField95: TIntegerField;
    IntegerField96: TIntegerField;
    IntegerField97: TIntegerField;
    IntegerField98: TIntegerField;
    IntegerField99: TIntegerField;
    stat7: TADOQuery;
    AutoIncField7: TAutoIncField;
    WideStringField7: TWideStringField;
    IntegerField100: TIntegerField;
    IntegerField101: TIntegerField;
    IntegerField102: TIntegerField;
    IntegerField103: TIntegerField;
    IntegerField104: TIntegerField;
    IntegerField105: TIntegerField;
    IntegerField106: TIntegerField;
    IntegerField107: TIntegerField;
    IntegerField108: TIntegerField;
    IntegerField109: TIntegerField;
    IntegerField110: TIntegerField;
    IntegerField111: TIntegerField;
    IntegerField112: TIntegerField;
    IntegerField113: TIntegerField;
    IntegerField114: TIntegerField;
    IntegerField115: TIntegerField;
    IntegerField116: TIntegerField;
    stat8: TADOQuery;
    AutoIncField8: TAutoIncField;
    WideStringField8: TWideStringField;
    IntegerField117: TIntegerField;
    IntegerField118: TIntegerField;
    IntegerField119: TIntegerField;
    IntegerField120: TIntegerField;
    IntegerField121: TIntegerField;
    IntegerField122: TIntegerField;
    IntegerField123: TIntegerField;
    IntegerField124: TIntegerField;
    IntegerField125: TIntegerField;
    IntegerField126: TIntegerField;
    IntegerField127: TIntegerField;
    IntegerField128: TIntegerField;
    IntegerField129: TIntegerField;
    IntegerField130: TIntegerField;
    IntegerField131: TIntegerField;
    IntegerField132: TIntegerField;
    IntegerField133: TIntegerField;
    stat10: TADOQuery;
    AutoIncField9: TAutoIncField;
    WideStringField9: TWideStringField;
    IntegerField134: TIntegerField;
    IntegerField135: TIntegerField;
    IntegerField136: TIntegerField;
    IntegerField137: TIntegerField;
    IntegerField138: TIntegerField;
    IntegerField139: TIntegerField;
    IntegerField140: TIntegerField;
    IntegerField141: TIntegerField;
    IntegerField142: TIntegerField;
    IntegerField143: TIntegerField;
    IntegerField144: TIntegerField;
    IntegerField145: TIntegerField;
    IntegerField146: TIntegerField;
    IntegerField147: TIntegerField;
    IntegerField148: TIntegerField;
    IntegerField149: TIntegerField;
    IntegerField150: TIntegerField;
    stat9: TADOQuery;
    AutoIncField10: TAutoIncField;
    WideStringField10: TWideStringField;
    IntegerField151: TIntegerField;
    IntegerField152: TIntegerField;
    IntegerField153: TIntegerField;
    IntegerField154: TIntegerField;
    IntegerField155: TIntegerField;
    IntegerField156: TIntegerField;
    IntegerField157: TIntegerField;
    IntegerField158: TIntegerField;
    IntegerField159: TIntegerField;
    IntegerField160: TIntegerField;
    IntegerField161: TIntegerField;
    IntegerField162: TIntegerField;
    IntegerField163: TIntegerField;
    IntegerField164: TIntegerField;
    IntegerField165: TIntegerField;
    IntegerField166: TIntegerField;
    IntegerField167: TIntegerField;
    stat11: TADOQuery;
    AutoIncField11: TAutoIncField;
    WideStringField11: TWideStringField;
    IntegerField168: TIntegerField;
    IntegerField169: TIntegerField;
    IntegerField170: TIntegerField;
    IntegerField171: TIntegerField;
    IntegerField172: TIntegerField;
    IntegerField173: TIntegerField;
    IntegerField174: TIntegerField;
    IntegerField175: TIntegerField;
    IntegerField176: TIntegerField;
    IntegerField177: TIntegerField;
    IntegerField178: TIntegerField;
    IntegerField179: TIntegerField;
    IntegerField180: TIntegerField;
    IntegerField181: TIntegerField;
    IntegerField182: TIntegerField;
    IntegerField183: TIntegerField;
    IntegerField184: TIntegerField;
    stat12: TADOQuery;
    AutoIncField12: TAutoIncField;
    WideStringField12: TWideStringField;
    IntegerField185: TIntegerField;
    IntegerField186: TIntegerField;
    IntegerField187: TIntegerField;
    IntegerField188: TIntegerField;
    IntegerField189: TIntegerField;
    IntegerField190: TIntegerField;
    IntegerField191: TIntegerField;
    IntegerField192: TIntegerField;
    IntegerField193: TIntegerField;
    IntegerField194: TIntegerField;
    IntegerField195: TIntegerField;
    IntegerField196: TIntegerField;
    IntegerField197: TIntegerField;
    IntegerField198: TIntegerField;
    IntegerField199: TIntegerField;
    IntegerField200: TIntegerField;
    IntegerField201: TIntegerField;
    annexe_v: TADOQuery;
    AutoIncField13: TAutoIncField;
    IntegerField202: TIntegerField;
    WideStringField13: TWideStringField;
    WideStringField14: TWideStringField;
    WideStringField15: TWideStringField;
    DateTimeField1: TDateTimeField;
    WideStringField16: TWideStringField;
    WideStringField17: TWideStringField;
    WideStringField18: TWideStringField;
    WideStringField19: TWideStringField;
    WideStringField20: TWideStringField;
    WideStringField21: TWideStringField;
    WideStringField22: TWideStringField;
    IntegerField203: TIntegerField;
    WideStringField23: TWideStringField;
    IntegerField204: TIntegerField;
    WideStringField24: TWideStringField;
    WideStringField25: TWideStringField;
    WideStringField26: TWideStringField;
    WideStringField27: TWideStringField;
    WideStringField28: TWideStringField;
    WideStringField29: TWideStringField;
    WideStringField30: TWideStringField;
    WideStringField31: TWideStringField;
    WideStringField32: TWideStringField;
    WideStringField33: TWideStringField;
    WideStringField34: TWideStringField;
    WideStringField35: TWideStringField;
    WideStringField36: TWideStringField;
    injectionvm: TIntegerField;
    injectionvy: TIntegerField;
    injection1: TADOQuery;
    AutoIncField15: TAutoIncField;
    WideStringField39: TWideStringField;
    IntegerField207: TIntegerField;
    WideStringField40: TWideStringField;
    WideStringField41: TWideStringField;
    WideStringField42: TWideStringField;
    IntegerField208: TIntegerField;
    IntegerField209: TIntegerField;
    IntegerField210: TIntegerField;
    vaccin1: TADOQuery;
    vaccin1vaccin_id: TAutoIncField;
    vaccin1vaccin_name: TWideStringField;
    vaccin1vaccin_lot: TWideStringField;
    vaccin1vaccin_month: TIntegerField;
    vaccin1vaccin_no: TIntegerField;
    procedure childCalcFields(DataSet: TDataSet);
    procedure vaccinCalcFields(DataSet: TDataSet);
    procedure injectionCalcFields(DataSet: TDataSet);
    procedure vaccin1CalcFields(DataSet: TDataSet);
    procedure childAfterEdit(DataSet: TDataSet);
    procedure childAfterInsert(DataSet: TDataSet);
    procedure childAfterPost(DataSet: TDataSet);



  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  data: Tdata;

implementation
    uses main;
{%CLASSGROUP 'Vcl.Controls.TControl'}

{$R *.dfm}



procedure Tdata.childAfterEdit(DataSet: TDataSet);
begin
data.years.Refresh;
form2.ComboBox1.Refresh;
end;

procedure Tdata.childAfterInsert(DataSet: TDataSet);
begin
data.years.Refresh;
form2.ComboBox1.Refresh;
end;

procedure Tdata.childAfterPost(DataSet: TDataSet);
begin
data.years.Refresh;
form2.ComboBox1.Refresh;
end;

procedure Tdata.childCalcFields(DataSet: TDataSet);
var s,v,k:integer;
begin
child['child_num']:=child.RecNo;
child['fullname']:=child['child_ln']+' '+child['child_fn'];
s:=monthsbetween(now,data.childchild_birth.Value);
k:= s mod 12;
v:= s div 12;
if v > 0 then
  child.fieldbyname('age').Value:=inttostr(v) + ' ⁄«„ Ê ' + inttostr(k) + ' ‘Â— '
else
   child.fieldbyname('age').Value:= inttostr(k) + ' ‘Â— ';

end;





procedure Tdata.injectionCalcFields(DataSet: TDataSet);
begin
injection['vm']:=MonthOf(mdata.data.injection.FieldByName('injection_date').Value);
end;



procedure Tdata.vaccin1CalcFields(DataSet: TDataSet);
begin
vaccin1['vaccin_no']:=vaccin1.RecNo;
end;

procedure Tdata.vaccinCalcFields(DataSet: TDataSet);
begin
vaccin['vaccin_num']:=vaccin.RecNo;
end;

end.
